### ISSUE TITLE
CRUD Operations in MongoDB

### ISSUE THREAD

**Issue by mjunedi** [thinkarlabs/P23-002-HealthKiosk#7]
Story1: Get JavaScript code with CRUD operations on MongoDB for insert, Read, Delete and Update commands

**Comment by basumadiwalar** [comment]
Inserting new document to the mongo db using node js is working fine.

*

async function Insert1(client){
    const database = client.db("DB1");

const Iteams = database.collection("Emids");
const doc = {
    title: "Record of a Shriveled Datum",
    content: "No bytes, no problem. Just insert a document, in MongoDB",
  }


const data = Iteams.insertOne(doc);
//data.insertOne(db => console.log(` -"having id: " ${db._id }," with name: " ${db.Name} ,${db.Contact} ,${db.Department},${db.Location}`));

console.log(doc);

};

**Comment by basumadiwalar** [comment]
Crud operation with node js is working fine
